-- CreateTable
CREATE TABLE todo (
    id INTEGER NOT NULL AUTO_INCREMENT,
    text VARCHAR(500) NOT NULL,
    completedAt DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

